window.addEventListener('load', function(){
// ===== Storage Keys (v3) + Migration
const LS={ENTRIES:'inbody.entries.v3',HEIGHT:'inbody.height.v3',GOALS:'inbody.goals.v3',WATER:'inbody.water.v3',THEME:'inbody.theme.v3',PIN:'inbody.pin.v3'};(function(){if(localStorage.getItem(LS.ENTRIES))return;const c=['inbody.entries.v2','inbody.entries.v1'];for(const k of c){const v=localStorage.getItem(k);if(v){localStorage.setItem(LS.ENTRIES,v);break}}const h=localStorage.getItem('inbody.height.v2')||localStorage.getItem('inbody.height.v1');if(h)localStorage.setItem(LS.HEIGHT,h);const g=localStorage.getItem('inbody.goals.v2')||localStorage.getItem('inbody.goals.v1');if(g)localStorage.setItem(LS.GOALS,g);const w=localStorage.getItem('inbody.water.v2')||localStorage.getItem('inbody.water.v1');if(w)localStorage.setItem(LS.WATER,w);})();
// Helpers
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);function todayISO(){return new Date().toISOString().slice(0,10)}function parseF(v){const x=parseFloat(v);return Number.isFinite(x)?x:null}function uid(){return Math.random().toString(36).slice(2)}function nf(x){return x==null?'—':Number(x).toFixed(1)}function save(k,v){localStorage.setItem(k,JSON.stringify(v))}function load(k,f=null){try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch{return f}}
// Tabs
const tabs=$$('.tab');const views=['dashboard','add','goals','water','history','settings'];function show(v){views.forEach(id=>{const el=document.getElementById('view-'+id);if(el)el.classList.toggle('active',id===v)});tabs.forEach(t=>t.classList.toggle('active',t.dataset.view===v));location.hash=v}tabs.forEach(t=>t.addEventListener('click',()=>show(t.dataset.view)));window.addEventListener('hashchange',()=>show(location.hash.replace('#','')||'dashboard'));
// Theme
function setTheme(name){document.documentElement.setAttribute('data-theme',name);save(LS.THEME,name);$('#themeName').textContent=(name==='light'?'فاتح':'غامق')}const pref=load(LS.THEME,(window.matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'));setTheme(pref);$('#btnTheme').onclick=()=>setTheme(document.documentElement.getAttribute('data-theme')==='light'?'dark':'light');
// Install prompt
let deferredPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#btnInstall').disabled=false});$('#btnInstall').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null}}
// Elements
const el={date:$('#date'),weight:$('#weight'),bodyFat:$('#bodyFat'),muscle:$('#muscle'),water:$('#water'),visceral:$('#visceral'),bmr:$('#bmr'),bmi:$('#bmi'),notes:$('#notes'),saveBtn:$('#saveBtn'),cancelBtn:$('#cancelBtn'),kpiWeight:$('#kpiWeight'),kpiBodyFat:$('#kpiBodyFat'),kpiBMI:$('#kpiBMI'),deltaWeight:$('#deltaWeight'),deltaBodyFat:$('#deltaBodyFat'),kpiGoal:$('#kpiGoal'),deltaGoal:$('#deltaGoal'),goalWeight:$('#goalWeight'),goalBodyFat:$('#goalBodyFat'),goalWeekly:$('#goalWeekly'),goalDeadline:$('#goalDeadline'),saveGoals:$('#saveGoals'),clearGoals:$('#clearGoals'),etaText:$('#etaText'),waterGoal:$('#waterGoal'),waterCustom:$('#waterCustom'),addCustom:$('#addCustom'),waterRing:$('#waterRing'),waterPct:$('#waterPct'),waterReset:$('#waterReset'),waterNotify:$('#waterNotify'),icsBtn:$('#icsBtn'),searchNotes:$('#searchNotes'),tableBody:$('#table tbody'),exportBtn:$('#exportBtn'),importBtn:$('#importBtn'),importFile:$('#importFile'),height:$('#height'),pin:$('#pin'),saveSettings:$('#saveSettings'),clearAll:$('#clearAll')};
// Height + BMI
function updateBMI(){const w=parseF(el.weight.value);const h=parseF(el.height.value)/100;el.bmi.value=(w&&h)?(w/(h*h)).toFixed(1):''}['weight','height'].forEach(id=>document.addEventListener('input',ev=>{if(ev.target.id===id)updateBMI()}));
// Entries
function getEntries(){return(load(LS.ENTRIES,[])).sort((a,b)=>a.date.localeCompare(b.date))}function saveEntries(list){save(LS.ENTRIES,list)}function resetForm(){window.editingId=null;el.date.value=todayISO();['weight','bodyFat','muscle','water','visceral','bmr','notes'].forEach(id=>el[id].value='');updateBMI()}function fillForm(e){el.date.value=e.date;el.weight.value=e.weightKg??'';el.bodyFat.value=e.bodyFatPct??'';el.muscle.value=e.muscleKg??'';el.water.value=e.waterPct??'';el.visceral.value=e.visceralFat??'';el.bmr.value=e.bmr??'';el.notes.value=e.notes??'';updateBMI();show('add');window.scrollTo({top:0,behavior:'smooth'})}
el.saveBtn.onclick=()=>{const list=getEntries();const obj={id:(window.editingId||uid()),date:el.date.value,weightKg:parseF(el.weight.value),bodyFatPct:parseF(el.bodyFat.value),muscleKg:parseF(el.muscle.value),waterPct:parseF(el.water.value),visceralFat:parseF(el.visceral.value),bmr:el.bmr.value?parseInt(el.bmr.value):null,bmi:el.bmi.value?parseFloat(el.bmi.value):null,notes:el.notes.value?.trim()||''};if(!obj.date)return alert('اختر تاريخًا');if(obj.weightKg==null)return alert('الوزن مطلوب');const others=list.filter(x=>x.id!==obj.id);others.push(obj);others.sort((a,b)=>a.date.localeCompare(b.date));saveEntries(others);window.editingId=null;resetForm();renderAll();show('history')};el.cancelBtn.onclick=()=>{window.editingId=null;resetForm()};$$('.chip[data-preset]').forEach(c=>c.onclick=()=>{const p=c.dataset.preset;const dt=new Date();if(p==='today'){}else{dt.setDate(dt.getDate()+Number(p))}el.date.value=dt.toISOString().slice(0,10)});
// KPIs + Chart
let chart,showAvg=false,range='all';function computeMovingAvg(arr,n=7){const out=[];for(let i=0;i<arr.length;i++){const w=arr.slice(Math.max(0,i-n+1),i+1).filter(x=>x!=null);out.push(!w.length?null:(w.reduce((a,b)=>a+b,0)/w.length))}return out}function filterByRange(entries,days){if(days==='all')return entries;const cutoff=new Date();cutoff.setDate(cutoff.getDate()-Number(days));return entries.filter(e=>new Date(e.date)>=cutoff)}function renderChart(){const all=getEntries();const entries=filterByRange(all,range);const labels=entries.map(e=>e.date);const weight=entries.map(e=>e.weightKg??null);const bodyFat=entries.map(e=>e.bodyFatPct??null);const weightAvg=showAvg?computeMovingAvg(weight,7):null;const ctx=document.getElementById('chart');if(!chart){chart=new Chart(ctx,{type:'line',data:{labels,datasets:[{label:'الوزن (كجم)',data:weight,tension:.35,yAxisID:'y'},{label:'دهون %',data:bodyFat,tension:.35,yAxisID:'y1'},{label:'متوسط 7 أيام',data:weightAvg||[],tension:.35,yAxisID:'y',borderDash:[6,4],hidden:!showAvg}]},options:{responsive:true,scales:{y:{position:'right'},y1:{position:'left',grid:{drawOnChartArea:false}}}})}else{chart.data.labels=labels;chart.data.datasets[0].data=weight;chart.data.datasets[1].data=bodyFat;chart.data.datasets[2].data=weightAvg||[];chart.data.datasets[2].hidden=!showAvg;chart.update()}}
$$('#view-dashboard .chip[data-range]').forEach(c=>c.onclick=()=>{$$('#view-dashboard .chip[data-range]').forEach(x=>x.classList.remove('active'));c.classList.add('active');range=c.dataset.range;renderChart()});$('#toggleAvg').onclick=e=>{showAvg=!showAvg;e.target.classList.toggle('active',showAvg);renderChart()};function renderKPIs(){const entries=getEntries();const h=parseF(el.height.value)/100;const latest=entries[entries.length-1],prev=entries[entries.length-2];if(latest){el.kpiWeight.textContent=nf(latest.weightKg);el.kpiBodyFat.textContent=nf(latest.bodyFatPct);el.kpiBMI.textContent=(h&&latest.weightKg)?(latest.weightKg/(h*h)).toFixed(1):'—';if(prev&&prev.weightKg!=null){const d=latest.weightKg-prev.weightKg;el.deltaWeight.textContent=`${d>0?'+':''}${d.toFixed(1)} كجم من آخر قراءة`;el.deltaWeight.className='delta '+(d>0?'up':d<0?'down':'')}else{el.deltaWeight.textContent=''}if(prev&&prev.bodyFatPct!=null){const d=latest.bodyFatPct-prev.bodyFatPct;el.deltaBodyFat.textContent=`${d>0?'+':''}${(d).toFixed(1)}٪`;el.deltaBodyFat.className='delta '+(d>0?'up':d<0?'down':'')}else{el.deltaBodyFat.textContent=''}}else{el.kpiWeight.textContent='—';el.kpiBodyFat.textContent='—';el.kpiBMI.textContent='—';el.deltaWeight.textContent='';el.deltaBodyFat.textContent=''}const g=loadGoals();if(g.weight&&latest?.weightKg){const diff=g.weight-latest.weightKg;el.kpiGoal.textContent=`${diff>0?'-':''}${Math.abs(diff).toFixed(1)} كجم`;el.deltaGoal.textContent='المتبقي للوصول للوزن المستهدف'}else if(g.bodyFat&&latest?.bodyFatPct){const diff=g.bodyFat-latest.bodyFatPct;el.kpiGoal.textContent=`${diff>0?'-':''}${Math.abs(diff).toFixed(1)}٪`;el.deltaGoal.textContent='المتبقي لنسبة الدهون المستهدفة'}else{el.kpiGoal.textContent='—';el.deltaGoal.textContent=''}}
// Goals
function loadGoals(){return load(LS.GOALS,{weight:null,bodyFat:null,weekly:null,deadline:null})}function saveGoals(g){save(LS.GOALS,g);renderGoals(g);renderKPIs()}function renderGoals(g){el.goalWeight.value=g.weight??'';el.goalBodyFat.value=g.bodyFat??'';el.goalWeekly.value=g.weekly??'';el.goalDeadline.value=g.deadline??'';const entries=getEntries();const latest=entries[entries.length-1];let txt='';if(latest&&g.weight&&g.weekly){const weeks=Math.abs((latest.weightKg-g.weight)/g.weekly);txt=`تقدير: ${weeks.toFixed(1)} أسبوع للوصول للوزن المستهدف.`}el.etaText.textContent=txt}el.saveGoals.onclick=()=>{const g=loadGoals();g.weight=parseF(el.goalWeight.value);g.bodyFat=parseF(el.goalBodyFat.value);g.weekly=parseF(el.goalWeekly.value);g.deadline=el.goalDeadline.value||null;saveGoals(g)};el.clearGoals.onclick=()=>{saveGoals({weight:null,bodyFat:null,weekly:null,deadline:null})};
// Water
function waterState(){const d=load(LS.WATER,null);const today=todayISO();if(!d||d.date!==today){return{date:today,intake:0,goal:3000}}return d}function saveWater(s){save(LS.WATER,s);renderWater(s)}function renderWater(s){el.waterGoal.value=s.goal;const pct=Math.max(0,Math.min(100,Math.round((s.intake/Math.max(s.goal,1))*100)));el.waterPct.textContent=pct+'%';const deg=pct/100*360;el.waterRing.style.transform='rotate('+(deg-90)+'deg)'}function addWater(ml){const s=waterState();s.intake=Math.max(0,s.intake+ml);saveWater(s);if('Notification'in window&&Notification.permission==='granted'){new Notification('تم تسجيل الماء',{body:`أضفت ${ml} مل. الإجمالي: ${s.intake} / ${s.goal} مل`})}}
$$('.chip[data-add]').forEach(b=>b.onclick=()=>{const ml=parseInt(b.dataset.add);if(ml>0)addWater(ml)});el.addCustom.onclick=()=>{const v=parseInt(el.waterCustom.value||'0');if(v>0)addWater(v)};el.waterGoal.addEventListener('input',()=>{const s=waterState();s.goal=parseInt(el.waterGoal.value||'0')||3000;saveWater(s)});el.waterReset.onclick=()=>{const s=waterState();s.intake=0;saveWater(s)};let waterInterval=null;el.waterNotify.onclick=async()=>{if(!('Notification'in window))return alert('المتصفح لا يدعم الإشعارات');let perm=Notification.permission;if(perm!=='granted'){perm=await Notification.requestPermission()}if(perm!=='granted'){return alert('لم يتم السماح بالإشعارات')}if(waterInterval){clearInterval(waterInterval);waterInterval=null;el.waterNotify.textContent='تفعيل تذكير الماء';return}el.waterNotify.textContent='إيقاف تذكير الماء';waterInterval=setInterval(()=>{const s=waterState();new Notification('اشرب ماء 💧',{body:`تقدّمك اليوم: ${s.intake}/${s.goal} مل`})},90*60*1000)};el.icsBtn.onclick=()=>{const ics=`BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//InBody Ultra//Water Reminder//AR\nBEGIN:VEVENT\nUID:${uid()}@inbody-ultra\nDTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').split('.')[0]}Z\nSUMMARY:اشرب ماء 💧\nDESCRIPTION:تذكير دوري بشرب الماء.\nRRULE:FREQ=DAILY;INTERVAL=1\nDTSTART:${new Date().toISOString().replace(/[-:]/g,'').split('.')[0]}Z\nDURATION:PT0M\nBEGIN:VALARM\nTRIGGER:-PT0M\nREPEAT:1\nDURATION:PT120M\nACTION:DISPLAY\nDESCRIPTION:اشرب ماء\nEND:VALARM\nEND:VEVENT\nEND:VCALENDAR`.replace(/\n/g,'\r\n');const blob=new Blob([ics],{type:'text/calendar'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='water-reminder.ics';a.click();URL.revokeObjectURL(url)};
// History
let historyRange='all';function renderTable(){const q=el.searchNotes.value.trim().toLowerCase();let entries=getEntries();if(historyRange!=='all'){const cutoff=new Date();cutoff.setDate(cutoff.getDate()-Number(historyRange));entries=entries.filter(e=>new Date(e.date)>=cutoff)}if(q)entries=entries.filter(e=>(e.notes||'').toLowerCase().includes(q));el.tableBody.innerHTML='';for(const e of entries){const tr=document.createElement('tr');function td(v){const x=document.createElement('td');x.textContent=v;return x}tr.appendChild(td(e.date));tr.appendChild(td(nf(e.weightKg)));tr.appendChild(td(nf(e.bodyFatPct)));tr.appendChild(td(nf(e.muscleKg)));tr.appendChild(td(nf(e.waterPct)));tr.appendChild(td(nf(e.visceralFat)));tr.appendChild(td(e.bmr??'—'));tr.appendChild(td(e.bmi??'—'));tr.appendChild(td(e.notes||'—'));const actions=document.createElement('td');actions.style.display='flex';actions.style.gap='6px';const b1=document.createElement('button');b1.textContent='تعديل';b1.className='ghost';b1.onclick=()=>{window.editingId=e.id;fillForm(e)};const b2=document.createElement('button');b2.textContent='حذف';b2.className='ghost';b2.onclick=()=>{if(confirm('حذف هذه القراءة؟')){const out=getEntries().filter(x=>x.id!==e.id);saveEntries(out);renderAll()}};actions.appendChild(b1);actions.appendChild(b2);tr.appendChild(actions);el.tableBody.appendChild(tr)}}
$('#searchNotes').addEventListener('input',renderTable);$$('#view-history .chip[data-range]').forEach(c=>c.onclick=()=>{$$('#view-history .chip[data-range]').forEach(x=>x.classList.remove('active'));c.classList.add('active');historyRange=c.dataset.range;renderTable()});
// Export/Import
el.exportBtn.onclick=()=>{const data=JSON.stringify({heightCm:parseF(el.height.value)||null,goals:loadGoals(),water:load(LS.WATER,null),entries:getEntries()},null,2);const blob=new Blob([data],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`inbody-ultra-${todayISO()}.json`;a.click();URL.revokeObjectURL(url)};el.importBtn.onclick=()=>el.importFile.click();el.importFile.onchange=(ev)=>{const f=ev.target.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{const pkg=JSON.parse(reader.result);if(pkg.heightCm!=null){el.height.value=pkg.heightCm;save(LS.HEIGHT,pkg.heightCm)}if(pkg.goals){save(LS.GOALS,pkg.goals)}if(pkg.water){save(LS.WATER,pkg.water)}if(Array.isArray(pkg.entries)){save(LS.ENTRIES,pkg.entries)}renderAll()}catch(e){alert('ملف JSON غير صالح')}};reader.readAsText(f)};
// Settings
function loadSettings(){const h=load(LS.HEIGHT,null);if(h!=null)el.height.value=h;const p=load(LS.PIN,null);if(p)el.pin.value=p}el.saveSettings.onclick=()=>{if(el.height.value)save(LS.HEIGHT,parseF(el.height.value));if(el.pin.value&&(el.pin.value.length<4||el.pin.value.length>6))return alert('PIN بين 4 و6 أرقام');if(el.pin.value)save(LS.PIN,el.pin.value);alert('تم الحفظ')};el.clearAll.onclick=()=>{if(confirm('هل أنت متأكد؟ سيُمسح كل شيء.')){Object.values(LS).forEach(k=>localStorage.removeItem(k));location.reload()}};
// Init
function renderAll(){renderKPIs();renderChart();renderTable();renderGoals(loadGoals());renderWater(waterState())}
(function(){const pin=load(LS.PIN,null);if(pin){const entered=prompt('أدخل PIN لفتح التطبيق');if(entered!==pin){alert('PIN غير صحيح');location.reload();return}}el.date.value=todayISO();loadSettings();show(location.hash.replace('#','')||'dashboard');renderAll();if('serviceWorker'in navigator){navigator.serviceWorker.register('sw.js')}})();
});